library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
package memoryMapLibrary is
constant CTR: integer:=  0 ; --Control
constant FLG: integer:=  63 ; --Status
constant ACC: integer:=  49 ; --Accepted commands
constant RCC: integer:=  50 ; --Rejected commands
constant LAC: integer:=  51 ; --Last acepted command
constant LRC: integer:=  52 ; --Last rejected command
constant FRC: integer:=  53 ; --Free running counter
constant VER: integer:=  54 ; --Core version
constant WRS: integer:=  55 ; --Write accesses
constant WRA: integer:=  56 ; --Last write Address
constant CAL: integer:=  32 ; --Calibration diode
constant PO1: integer:=  33 ; --Power on/off 1
constant PO2: integer:=  34 ; --Power on/off 2
constant PO3: integer:=  35 ; --Power on/off 3
constant PO4: integer:=  36 ; --LD TEC Power on/off
constant LTMa: integer:=  96 ; --TEC Measured Temp (MSB)
constant LTMb: integer:=  97 ; --TEC Measured Temp (LSB)
constant TE1a: integer:=  98 ; --Temperature 1 (MSB)
constant TE1b: integer:=  99 ; --Temperature 1 (LSB)
constant TE2a: integer:=  100 ; --Temperature 2 (MSB)
constant TE2b: integer:=  101 ; --Temperature 2 (LSB)
constant TE3a: integer:=  102 ; --Temperature 3 (MSB)
constant TE3b: integer:=  103 ; --Temperature 3 (LSB)
constant TE4a: integer:=  104 ; --Temperature 4 (MSB)
constant TE4b: integer:=  105 ; --Temperature 4 (LSB)
constant TE5a: integer:=  106 ; --Temperature 5 (MSB)
constant TE5b: integer:=  107 ; --Temperature 5 (LSB)
constant TE6a: integer:=  108 ; --Temperature 6 (MSB)
constant TE6b: integer:=  109 ; --Temperature 6 (LSB)
constant CC1a: integer:=  110 ; --Current Consumption LD Bias (MSB)
constant CC1b: integer:=  111 ; --Current Consumption LD Bias (LSB)
constant CC2a: integer:=  112 ; --Current Consumption TEC (MSB)
constant CC2b: integer:=  113 ; --Current Consumption TEC (LSB)
constant CC3a: integer:=  114 ; --Current Consumption HEATER (MSB)
constant CC3b: integer:=  115 ; --Current Consumption HEATER (LSB)
constant CC4a: integer:=  116 ; --Current Consumption EDFA (MSB)
constant CC4b: integer:=  117 ; --Current Consumption EDFA (LSB)
constant HE1: integer:=  37 ; --Heater 1 on/off
constant HE2: integer:=  38 ; --Heater 2 on/off
constant LTSa: integer:=  1 ; --Temp  Set Point(MSB)
constant LTSb: integer:=  2 ; --Temp  Set Poin  (LSB)
constant LBCa: integer:=  3 ; --Bias Current (MSB)
constant LBCb: integer:=  4 ; --Bias Current (LSB)
constant THRa: integer:=  5 ; --Threshold configuration
constant THRb: integer:=  6 ; --
constant THRc: integer:=  7 ; --
constant PDI: integer:=  64 ; --Power level
constant FSMa: integer:=  8 ; --FSM configuration
constant FSMb: integer:=  9 ; --
constant FSMc: integer:=  10 ; --
constant ETX: integer:=  11 ; --UART Tx
constant ERX: integer:=  65 ; --UART Rx
constant SEP: integer:=  12 ; --Error Period
constant SCE: integer:=  66 ; --Corrected Errors
constant SIE: integer:=  67 ; --Inserted Errors
constant SST: integer:=  68 ; --SEM Status
constant DAT: integer:=  13 ; --PPM order / Data
constant DEL: integer:=  14 ; --Delay
constant FFF: integer:=  57 ; --FIFOs Flags
constant ERR: integer:=  58 ; --Errors
constant ONE: integer:=  59 ; --Ones
constant DFP: integer:=  60 ; --Data FIFO Pointer
constant EFP: integer:=  61 ; --Errors FIFO Pointer
constant OFP: integer:=  62 ; --Ones FIFO Pointer
end package;
