# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories true

set tclUtilsPath "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "Z:/HDL/Repo/node-fpga_mitfork/controller/controller.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "z:/HDL/Repo/node-fpga_mitfork/controller/controller.srcs/sources_1/ip/sem_v3_6_0/coregen.cgc"

set ipFile "z:/HDL/Repo/node-fpga_mitfork/controller/controller.srcs/sources_1/ip/sem_v3_6_0/sem_v3_6_0.xco"

set ipName "sem_v3_6_0"

set hdlType "VHDL"

set cgPartSpec "xc6slx9-3tqg144"

set chains "GENERATE_CURRENT_CHAIN"

set params ""

set bomFilePath "z:/HDL/Repo/node-fpga_mitfork/controller/controller.srcs/sources_1/ip/sem_v3_6_0/pa_cg_bom.xml"

# generate the IP
set result [source "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_gen_out_prods.tcl"]

exit $result

