# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories false

set tclUtilsPath "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "Z:/HDL/Repo/node-fpga_mitfork/controller/controller.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "z:/HDL/Repo/node-fpga_mitfork/controller/controller.srcs/sources_1/ip/sem_v3_6_0/coregen.cgc"

set ipFile "z:/HDL/Repo/node-fpga_mitfork/controller/controller.srcs/sources_1/ip/sem_v3_6_0/sem_v3_6_0.xco"

set ipName "sem_v3_6_0"

set chains "CUSTOMIZE_CURRENT_CHAIN INSTANTIATION_TEMPLATES_CHAIN"

set bomFilePath "z:/HDL/Repo/node-fpga_mitfork/controller/controller.srcs/sources_1/ip/sem_v3_6_0/pa_cg_bom.xml"

set cgPartSpec "xc6slx9-3tqg144"

set hdlType "VHDL"

# generate the IP
set result [source "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_reconfig_core.tcl"]

exit $result

