# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories false

set tclUtilsPath "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "C:/Users/nn_w7/Desktop/Controller/controller.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "c:/Users/nn_w7/Desktop/Controller/controller.srcs/sources_1/ip/fifo_generator_v9_3_0/coregen.cgc"

set ipFile "c:/Users/nn_w7/Desktop/Controller/controller.srcs/sources_1/ip/fifo_generator_v9_3_0/fifo_generator_v9_3_0.xco"

set ipName "fifo_generator_v9_3_0"

set chains "CUSTOMIZE_CURRENT_CHAIN INSTANTIATION_TEMPLATES_CHAIN"

set bomFilePath "c:/Users/nn_w7/Desktop/Controller/controller.srcs/sources_1/ip/fifo_generator_v9_3_0/pa_cg_bom.xml"

set cgPartSpec "xc6slx9-3tqg144"

set hdlType "VHDL"

# generate the IP
set result [source "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_reconfig_core.tcl"]

exit $result

